services:
  - type: web
    name: backend
    runtime: docker
    repo: https://github.com/angel-63/COMP4801
    branch: main
    rootDir: backend
    envVars:
      - key: MONGODB_URI
        sync: false
        fromSecret: MONGODB_URI
      - key: MONGODB_NAME
        value: job_db 
      - key: REDIS_PASSWORD
        sync: false
        fromSecret: REDIS_PASSWORD
      - key: JWT_SECRET
        sync: false
      - key: RECOMMENDER_URL
        value: http://recommender:8001

  - type: web
    name: recommender
    runtime: python
    repo: https://github.com/angel-63/COMP4801
    branch: main
    rootDir: recommender
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8001
    envVars:
      - key: MONGODB_URI
        sync: false
        fromSecret: MONGODB_URI
      - key: MONGODB_NAME
        value: job_db 