jwt:
  secret: TdL0EjB97Sz0yCb1CWKwnzmI1fzseb18wE5wQCXL6OG
  expiration: 360000 # 6mins, add one more 0 for 1hr

spring:
  application:
    name: jobportal
  mongodb:
    uri: ${MONGODB_URI}
    database: job_db
  data:
    mongodb:
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy

#recommender:
#  url: http://localhost:8001