jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000 # 5 0s 1hr; 4 0s 6min

spring:
  application:
    name: jobportal
  mongodb:
    uri: ${MONGODB_URI}
    database: job_db
  data:
    mongodb:
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
    redis:
      host: redis-17416.crce264.ap-east-1-1.ec2.cloud.redislabs.com
      port: 17416
      username: default
      password: ${REDIS_PASSWORD}

recommender:
  url: ${RECOMMENDER_URL:http://localhost:8001}