spring:
  application:
    name: jobportal
  mongodb:
    uri: ${MONGODB_URI}
    database: job_db
  data:
    mongodb:
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
#    security:
#      jwt:
#        secret: ${JWT_SECRET:mySuperSecretKey123}
#        expiration: 86400000
#recommendation:
#  service:
#    url: ${RECOMMENDER_URL:http://localhost:8001}