spring:
  application:
    name: jobportal
  mongodb:
    uri: ${MONGODB_URI}
    database: job_db
  data:
    mongodb:
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy

jwt:
  secret: d12c5960f72e477f014b10e9532c0bcb92c29dc828beba09e9e42eb743eddfca
  expiration: 360000 # 1hr
#recommender:
#  url: http://localhost:8001