name: Daily Job Scraper

on:
  schedule:
    - cron: '5 8/12 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        site: [linkedin, jobsdb]     # run in parallel
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      MONGODB_NAME: ${{ vars.MONGODB_NAME }}
    steps:
      - uses: actions/checkout@v6
        name: Checkout repository

      - uses: actions/setup-python@v6
        name: Set up Python
        with:
          python-version: '3.12.2'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Fetch list of working proxies
        run: |
          curl -s https://raw.githubusercontent.com/Thordata/awesome-free-proxy-list/main/proxies/all.txt > proxies.txt

      - name: Run scraper for site ${{ matrix.site }}
        run: |
          PROXIES=$(curl -s https://raw.githubusercontent.com/Thordata/awesome-free-proxy-list/main/proxies/all.txt | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+:[0-9]+$' | head -n 20 | paste -sd,)
          python run.py scraper --mode both --site ${{ matrix.site }} --proxies "$PROXIES"